name: finder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  intl: ^0.18.1
  firebase_messaging: ^15.2.4
  http: ^1.1.0
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.7
  google_maps_flutter: ^2.2.0
  geolocator: ^10.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/NSBM_logo.png
    - assets/campus.png
    - assets/location.png
    - assets/calendar.png
    - assets/list.png
    - assets/classroom.png
    - assets/contact.png
    - assets/about.png
    - assets/lecturer.png
    - assets/student.png
    - assets/Home.jpg
    - assets/appointment.png
    - assets/inbox.png
    - assets/Switch.png
    - assets/campus_large.png
