name: finder
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/NSBM_logo.png
    - assets/campus.png
    - assets/location.png
    - assets/calendar.png
    - assets/list.png
    - assets/classroom.png
    - assets/contact.png
    - assets/about.png
    - assets/lecturer.png
    - assets/student.png
